#!/bin/bash

# shellcheck source=/dev/null
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/test-lib.sh
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/test-lib-mongodb.sh

#
# General test for MongoDB image.
#
# Always use sourced from a specific container testfile

function ctest_general() {
    USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" test_general admin
    # Test with random uid in container
    CONTAINER_ARGS="-u 12345" USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" test_general admin_altuid
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  ct_init
  ctest_general "$@"
  ct_finish
fi

# vim: set tabstop=2:shiftwidth=2:expandtab:
